@startuml

left to right direction
title Визульная система РЖД расписания

actor :Пользователь: as User
actor :Оператор: as Operator
actor :Администратор: as Administrator

Administrator -- (Редактировать список операторов)
(Редактировать список операторов) <|-- (Добавить оператора)
(Редактировать список операторов) <|-- (Удалить оператора)
Administrator -- (Авторизация в системе)
Administrator -- (Просмотр карты)

Operator -- (Авторизация в системе)
Operator -- (Редактирование карты)
(Редактирование карты) <|-- (Добавление станций)
(Редактирование карты) <|-- (Удаление станций)
(Редактирование карты) <|-- (Добавить пути между станциями)
Operator -- (Редактирование информации о станции)
Operator -- (Редактирование расписания)
(Редактирование расписания) <|-- (Добавление маршрута)
(Редактирование расписания) <|-- (Удаление маршрута)
(Редактирование расписания) <|-- (Редактирование информации о маршруте в пути)
Operator -- (Редактирование списка действующих поездов)
(Редактирование списка действующих поездов) <|-- (Добавление поеда)
(Редактирование списка действующих поездов) <|-- (Удаление поезда)
(Редактирование списка действующих поездов) <|-- (Редактирование информации о пoезде)
Operator -- (Просмотр карты)

usecase GetRouteList as "Получение списка маршрутов между станциями
--
<b>Точки расширения</b>
Сортировка маршрутов"

User -- GetRouteList
GetRouteList <.. (Сортировка списка по различным критериям) : extend
User -- (Просмотр карты)

@enduml
